config/routes.rb
Rails.application.routes.draw do
  resources :finances

  resources :quotes

  resources :inventories

  resources :customers

  resources :employees

   root 'employees#index'

end

app/models/finance.rb
class Finance < ActiveRecord::Base
  belongs_to :quote

  def self.calculate_loans_table(principal_by_pay = 0,payments = 0,interest_rates = 0)
    Rails.logger.debug "Inputs: #{principal_by_pay} #{payments} #{interest_rates}"
    financial = []
    (0..payments).each do |t|
      financial << interest_rates*principal_by_pay/((payments*12)*(1-(1+(interest_rates/payments*12))**-(payments*12)))
    end
    return financial # the word return is optional - could just put population
  end
  def calculate_loans_table
    return self.class.calculate_loans_table(self.principal_by_pay,self.payments,self.interest_rate)
  end


end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  # GET /finances
  # GET /finances.json
  def index
    @finances = Finance.all
  end

  # GET /finances/1
  # GET /finances/1.json
  def show
    @financial_array = @finance.calculate_loans_table
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to @finance, notice: 'Finance was successfully created.' }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1
  # PATCH/PUT /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to @finance, notice: 'Finance was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance.destroy
    respond_to do |format|
      format.html { redirect_to finances_url, notice: 'Finance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def financial
    rate = params[:rate]
    pay = params[:pay]
    principal = params[:pri]
    @financial_array = Finances.calculate_loans_table(principal.to_i, pay.to_i, rate.to_f)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_params
      params.require(:finance).permit(:quote_id, :principal_by_pay, :interest, :date, :interest_rate, :payments)
    end
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/_form.html.erb
<%= form_for(@finance) do |f| %>
  <% if @finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% @finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote_id %><br>
    <%= f.collection_select :quote_id, Quote.all, :id, :quote_info %>
  </div>
  <div class="field">
    <%= f.label :Loan %><br>
    <%= f.text_field :principal_by_pay %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :interest_rate %><br>
    <%= f.text_field :interest_rate %>
  </div>
  <div class="field">
    <%= f.label :Years %><br>
    <%= f.select :payments, [['3', '3'],['4', '4'],['5', '5']]%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<!-- Table will be inserted here -->
<div id="amortization-table" class="table-format"></div>

app/views/finances/_loans_table.erb
<table class="CSSTableGenerator" width="30%">
  <th>Year</th>
  <th>Amount</th>
  <% @financial_array.each_with_index do |p,n|  %>
      <tr>
        <td><%= n %></td>
        <td><%= p.round(2) %></td>
      </tr>
  <% end %>

</table>

app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form' %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/financial.js.erb
$('#amortization-table').html("<%= j (render 'loans_table') %>")

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Finances</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Principal by pay</th>
      <th>Date</th>
      <th>Interest rate</th>
      <th>Payments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finances.each do |finance| %>
      <tr>
        <td><%= finance.quote_id %></td>
        <td><%= finance.principal_by_pay %></td>
        <td><%= finance.date %></td>
        <td><%= finance.interest_rate %></td>
        <td><%= finance.payments %></td>
        <td><%= link_to 'Show', finance %></td>
        <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
        <td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Finance', new_finance_path %>

app/views/finances/new.html.erb
<h1>New Finance</h1>

<%= render 'form' %>

<%= link_to 'Back', finances_path %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @finance.quote_id %>
</p>

<p>
  <strong>Principal by pay:</strong>
  <%= @finance.principal_by_pay %>
</p>

<p>
  <strong>Date:</strong>
  <%= @finance.date %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= @finance.interest_rate %>
</p>

<p>
  <strong>Payments:</strong>
  <%= @finance.payments %>
</p>
<%= render 'loans_table' %>
<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>